//! Permisos de comandos propios de la app (ACL de Tauri v2).
//!
//! Sin un "app manifest", TODOS los comandos `#[command]` quedan invocables
//! desde cualquier ventana del WebView. Acá se declaran todos (la lista sale
//! de `generate_handler![...]` en `src/lib.rs`, la única fuente de verdad)
//! para que cada ventana tenga que recibir permiso explícito en su
//! capability (`capabilities/*.json`): la ventana principal usa el set
//! `app-commands-all` y la ventana de log solo unos pocos comandos sueltos.
//!
//! Tauri autogenera `allow-<comando>`/`deny-<comando>` por cada comando
//! (en `permissions/autogenerated/`, ignorado por git). El set
//! `app-commands-all` lo generamos nosotros en `permissions/app-commands.toml`
//! (también ignorado) con la misma lista, así agregar un comando nuevo a
//! `lib.rs` lo habilita solo para la ventana principal — nunca para las demás
//! sin que alguien lo pida a propósito en su capability.

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

/// Nombres de los comandos registrados en `generate_handler![...]`.
fn registered_commands(lib_rs: &str) -> Vec<String> {
    let Some(start) = lib_rs.find("generate_handler![") else {
        panic!("build.rs: no se encontró `generate_handler![` en src/lib.rs");
    };
    let rest = &lib_rs[start + "generate_handler![".len()..];
    let end = rest
        .find(']')
        .expect("build.rs: `generate_handler![` sin cerrar");
    let mut names = BTreeSet::new();
    for raw in rest[..end].split(',') {
        // Saca comentarios de línea que puedan haber quedado pegados al nombre.
        let cleaned: String = raw
            .lines()
            .map(|l| l.split("//").next().unwrap_or(""))
            .collect::<Vec<_>>()
            .join(" ");
        let entry = cleaned.trim();
        if entry.is_empty() {
            continue;
        }
        let name = entry.rsplit("::").next().unwrap_or(entry).trim();
        assert!(
            name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'),
            "build.rs: entrada rara en generate_handler!: `{entry}`"
        );
        names.insert(name.to_string());
    }
    names.into_iter().collect()
}

/// Identificador de permiso que Tauri genera para un comando
/// (`get_settings` → `allow-get-settings`).
fn allow_id(command: &str) -> String {
    format!("allow-{}", command.replace('_', "-"))
}

fn main() {
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=capabilities");

    let lib_rs = fs::read_to_string("src/lib.rs").expect("build.rs: no se pudo leer src/lib.rs");
    let commands = registered_commands(&lib_rs);
    assert!(
        commands.len() > 10,
        "build.rs: se encontraron muy pocos comandos ({}), el parser falló",
        commands.len()
    );

    // Set con todos los comandos propios, para la capability de la ventana
    // principal. Se escribe solo si cambió, así no se ensucia el árbol ni se
    // dispara un rebuild de más.
    let mut set = String::from(
        "# GENERADO por build.rs a partir de generate_handler! en src/lib.rs — no editar.\n",
    );
    set.push_str("[[set]]\nidentifier = \"app-commands-all\"\n");
    set.push_str(
        "description = \"Todos los comandos propios de TFL Client (solo ventana principal)\"\n",
    );
    set.push_str("permissions = [\n");
    for c in &commands {
        set.push_str(&format!("  \"{}\",\n", allow_id(c)));
    }
    set.push_str("]\n");

    let dir = Path::new("permissions");
    fs::create_dir_all(dir).expect("build.rs: no se pudo crear permissions/");
    let target = dir.join("app-commands.toml");
    if fs::read_to_string(&target).ok().as_deref() != Some(set.as_str()) {
        fs::write(&target, set).expect("build.rs: no se pudo escribir app-commands.toml");
    }

    // Los comandos que la ventana de log puede pedir tienen que existir de
    // verdad: un typo en su capability rompería la ventana en silencio.
    for allowed in LOG_WINDOW_COMMANDS {
        assert!(
            commands.iter().any(|c| c == allowed),
            "build.rs: LOG_WINDOW_COMMANDS menciona `{allowed}`, que no está en generate_handler!"
        );
    }

    let commands: &'static [&'static str] = Box::leak(
        commands
            .into_iter()
            .map(|c| &*Box::leak(c.into_boxed_str()))
            .collect::<Vec<&'static str>>()
            .into_boxed_slice(),
    );

    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(commands)),
    )
    .expect("error al generar el contexto de Tauri");
}

/// Comandos que usa `InstanceLogWindow.svelte` (ventana `log-*`). Si ese
/// componente empieza a usar otro comando, hay que sumarlo acá Y en
/// `capabilities/log-window.json` — el test `log_window_capability_*` en
/// `src/lib.rs` revisa que ambas listas coincidan.
const LOG_WINDOW_COMMANDS: &[&str] = &[
    "get_running_instance_stats",
    "stop_running_instance",
    "get_crash_report",
    "diagnose_crash",
    "set_mod_enabled",
    "rollback_mod_update",
];
