[package]
name = "tflclient"
version = "0.1.0"
description = "TFL Client, launcher de Minecraft de TFLives"
authors = ["TFLives"]
edition = "2024"

[lib]
name = "tflclient_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools", "protocol-asset"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
aqua = { path = "../crates/aqua" }
launchwerk = { path = "../crates/launchwerk", features = ["auth"] }
directories = "6.0.0"
tokio = { version = "1", features = ["sync", "rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
reqwest = { version = "0.13", features = ["json", "multipart"] }
sysinfo = "0.30"
uuid = { version = "1", features = ["v4"] }
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-dialog = "2"
tauri-plugin-window-state = "2"
thiserror = "2"
futures = "0.3"
zip = "8"
toml = "1"
base64 = "0.22"
infer = "0.19"
sha1 = "0.11"
notify = "8"
dashmap = "6"
parking_lot = "0.12"
cubrinth = { path = "../crates/cubrinth" }
zellkern = { path = "../crates/zellkern" }
communicator = { path = "../crates/communicator" }
compact_str = { version = "0.9", features = ["serde"] }
smallvec = "1"
ablage = { path = "../crates/ablage" }
postcard = { version = "1", features = ["use-std"] }
urlencoding = "2"
url = "2"
regex = "1"
tauri-plugin-opener = "2.5.5"
tauri-plugin-clipboard-manager = "2.3.3"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"
